# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 295a36119a04420308d5179419dcaddeff2df170bba7585ac879c2335d9359f3e483791892bda7beedbc2b132aa5a7efbe46dc65d7fcf73fa3310444c470e494

test:
  secret_key_base: 03efdd00d28d4f723bf8d8edf583a950cca7abe8d93e811d7abf0a41e0ad8678d135b67af593f9e1e1b75fd06344b99c35205c500d37755e29f4f46316c4f044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
