# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04aa6e189f320e29abff164501ec677b9aedcf05a08281c31346dcd4aeb40a2b531af44bb70d78b9c60a26f85a6bf8cb9bc6a8f0bf1e378f745ab8a22a47f8d2

test:
  secret_key_base: 72a8bf7e0eee567348405902b1fd86f59b1643aaa7a126b8f062041336830389a79f906c36842e921a906e262893cc416c20c8a8bc7de1f6d3115134f480bdba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
